version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    #hostname: my-rabbit
    #container_name: some-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
